INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Acrobatics', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Appraise', 'int', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Bluff', 'cha', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Climb', 'str', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Craft', 'int', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Diplomacy', 'cha', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Disable Device', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Disguise', 'cha', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Escape Artist', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Fly', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Handle Animal', 'cha', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Heal', 'wis', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Intimidate', 'cha', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Knowledge', 'int', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Linguistics', 'int', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Perception', 'wis', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Perform', 'cha', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Profession', 'wis', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Ride', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Sense Motive', 'wis', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Sleight of Hand', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Spellcraft', 'int', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Stealth', 'dex', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Survival', 'wis', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Swim', 'str', 1, 1, 1)
INSERT INTO "skills" ("name", "stat", "armor", "untrained", "multi") VALUES ('Use Magic Device', 'cha', 1, 1, 1)
